import React from 'react';
import { useLocation, useNavigate, useParams } from 'react-router-dom';
import {
  Activity, AlertTriangle, CheckCircle2, ChevronRight,
  History, FileText, Brain, ArrowLeft, User
} from 'lucide-react';
import { Breadcrumbs } from '../components/common/Breadcrumbs';
import { RiskBadge } from '../components/common/RiskBadge';
import { ConfidenceBar } from '../components/common/ConfidenceBar';
import { formatConfidence } from '../utils';
import type { Patient, PredictionResponse } from '../types';

export function PredictionResultPage() {
  const { patientId } = useParams<{ patientId: string }>();
  const navigate = useNavigate();
  const location = useLocation();

  const state = location.state as { result: PredictionResponse; patient?: Patient } | null;
  const result = state?.result;
  const patient = state?.patient;

  if (!result) {
    return (
      <div className="animate-fade-in text-center py-20">
        <Brain className="w-12 h-12 text-[color:var(--text-muted)] mx-auto mb-5" />
        <h2 className="text-lg font-semibold text-[color:var(--text-main)]">No prediction result found</h2>
        <p className="text-sm text-[color:var(--text-muted)] mt-2">
          Please run an EEG analysis to see results here.
        </p>
        <button
          onClick={() => navigate(`/prediction/${patientId}`)}
          className="btn-primary mt-8"
        >
          Start EEG Analysis
        </button>
      </div>
    );
  }

  const isSeizure = result.prediction.toLowerCase() === 'seizure';
  
  // Custom dark theme scheme for results
  const scheme = isSeizure
    ? {
        gradient: 'linear-gradient(135deg, rgba(248,113,113,0.1) 0%, rgba(153,27,27,0.2) 100%)',
        border: 'rgba(248,113,113,0.3)',
        glow: 'rgba(248,113,113,0.15)',
        text: '#fca5a5', // lighter red
        iconBg: 'rgba(248,113,113,0.15)',
        iconColor: '#f87171',
        icon: <AlertTriangle className="w-10 h-10" style={{ color: '#f87171' }} />
      }
    : {
        gradient: 'linear-gradient(135deg, rgba(52,211,153,0.1) 0%, rgba(6,95,70,0.2) 100%)',
        border: 'rgba(52,211,153,0.3)',
        glow: 'rgba(52,211,153,0.15)',
        text: '#6ee7b7', // lighter green
        iconBg: 'rgba(52,211,153,0.15)',
        iconColor: '#34d399',
        icon: <CheckCircle2 className="w-10 h-10" style={{ color: '#34d399' }} />
      };

  return (
    <div className="animate-fade-in max-w-4xl mx-auto space-y-6">
      <Breadcrumbs items={[
        { label: 'Patients', href: '/patients' },
        { label: result.patient_id, href: `/patients/${result.patient_id}` },
        { label: 'EEG Analysis', href: `/prediction/${result.patient_id}` },
        { label: 'Result' },
      ]} />

      <div className="page-header">
        <div>
          <h1 className="page-title">EEG Screening Result</h1>
          <p className="page-subtitle">
            {patient ? `${patient.name} · ` : ''}
            <code className="text-cyan-400 bg-cyan-950/30 px-1.5 py-0.5 rounded text-xs font-mono">
              {result.patient_id}
            </code>
          </p>
        </div>
        <button onClick={() => navigate(`/prediction/${patientId}`)} className="btn-secondary btn-sm">
          <ArrowLeft className="w-4 h-4" />
          New Analysis
        </button>
      </div>

      <div
        className="flex items-start gap-3 p-4 rounded-xl"
        style={{ background: 'rgba(56,189,248,0.06)', border: '1px solid rgba(56,189,248,0.15)' }}
      >
        <Activity className="w-5 h-5 text-sky-400 flex-shrink-0 mt-0.5" />
        <p className="text-sm text-sky-300/90 leading-relaxed">
          <strong className="text-sky-400">Screening result only.</strong> This prediction is generated by an AI model and is intended to support —
          not replace — professional clinical assessment by a qualified neurologist or physician.
        </p>
      </div>

      {/* Main Result Card */}
      <div
        className="rounded-2xl p-8 relative overflow-hidden"
        style={{
          background: scheme.gradient,
          border: `1px solid ${scheme.border}`,
          boxShadow: `0 0 40px ${scheme.glow}`,
          backdropFilter: 'blur(20px)',
        }}
      >
        <div className="absolute inset-0 bg-[url('https://www.transparenttextures.com/patterns/cubes.png')] opacity-10 mix-blend-overlay"></div>
        
        <div className="relative z-10 flex flex-col items-center text-center gap-6">
          <div
            className="w-20 h-20 rounded-2xl flex items-center justify-center shadow-lg"
            style={{ background: scheme.iconBg, border: `1px solid ${scheme.border}` }}
          >
            {scheme.icon}
          </div>

          <div>
            <p className="text-xs font-semibold uppercase tracking-widest text-[color:var(--text-muted)] mb-2">
              Model Output
            </p>
            <h2
              className="text-5xl md:text-6xl font-black tracking-tight mb-4"
              style={{ color: scheme.text, textShadow: `0 0 20px ${scheme.glow}` }}
            >
              {result.prediction.toUpperCase()}
            </h2>
            <RiskBadge risk={result.risk_level} size="lg" />
          </div>
        </div>
      </div>

      {/* Details Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Confidence */}
        <div className="card flex flex-col justify-center">
          <h3 className="text-sm font-semibold text-[color:var(--text-muted)] uppercase tracking-widest mb-6">Confidence Score</h3>
          <div className="flex items-end gap-2 mb-4">
            <span className="text-5xl font-bold text-[color:var(--text-main)] leading-none">
              {(result.confidence * 100).toFixed(1)}
            </span>
            <span className="text-2xl font-medium text-[color:var(--text-muted)] mb-1">%</span>
          </div>
          <ConfidenceBar confidence={result.confidence} showLabel={false} size="lg" />
        </div>

        {/* Patient Info */}
        <div className="card">
          <h3 className="text-sm font-semibold text-[color:var(--text-muted)] uppercase tracking-widest mb-5">Patient Information</h3>
          <div className="flex flex-col gap-3">
            <div className="flex justify-between items-center py-2" style={{ borderBottom: '1px solid var(--glass-bg-hover)' }}>
              <span className="text-sm text-[color:var(--text-muted)]">Patient ID</span>
              <span className="text-sm font-mono font-medium text-[color:var(--text-main)]">{result.patient_id}</span>
            </div>
            {patient && (
              <>
                <div className="flex justify-between items-center py-2" style={{ borderBottom: '1px solid var(--glass-bg-hover)' }}>
                  <span className="text-sm text-[color:var(--text-muted)]">Name</span>
                  <span className="text-sm font-medium text-[color:var(--text-main)]">{patient.name}</span>
                </div>
                <div className="flex justify-between items-center py-2" style={{ borderBottom: '1px solid var(--glass-bg-hover)' }}>
                  <span className="text-sm text-[color:var(--text-muted)]">Age</span>
                  <span className="text-sm font-medium text-[color:var(--text-main)]">{patient.age} years</span>
                </div>
                <div className="flex justify-between items-center py-2">
                  <span className="text-sm text-[color:var(--text-muted)]">Gender</span>
                  <span className="text-sm font-medium text-[color:var(--text-main)]">{patient.gender}</span>
                </div>
              </>
            )}
          </div>
        </div>
      </div>

      <div className="card">
        <h3 className="text-sm font-semibold text-[color:var(--text-muted)] uppercase tracking-widest mb-4">Risk Interpretation</h3>
        <div className="space-y-3 text-sm text-[color:var(--text-muted)] leading-relaxed">
          <p>
            <strong className="text-[color:var(--text-main)]">Prediction:</strong>{' '}
            {isSeizure
              ? 'The model has detected patterns consistent with seizure activity.'
              : 'The model has not detected patterns consistent with seizure activity.'}
          </p>
          <p>
            <strong className="text-[color:var(--text-main)]">Risk Level:</strong>{' '}
            {result.risk_level === 'High' && 'High risk — confidence ≥ 80% with seizure prediction.'}
            {result.risk_level === 'Moderate' && 'Moderate risk — confidence < 80% with seizure prediction.'}
            {result.risk_level === 'Low' && 'Low risk — no seizure pattern detected.'}
          </p>
          <p className="text-xs text-[color:var(--text-muted)] mt-4 pt-4" style={{ borderTop: '1px solid var(--glass-bg-hover)' }}>
            Risk levels are computed by the backend model. High: seizure predicted with confidence ≥ 80%.
            Moderate: seizure predicted with confidence &lt; 80%. Low: no seizure detected.
          </p>
        </div>
      </div>

      {/* Actions */}
      <div className="flex flex-wrap gap-4 pt-2">
        <button
          onClick={() => navigate(`/history/${result.patient_id}`)}
          className="btn-secondary"
        >
          <History className="w-4 h-4" />
          View History
        </button>
        <button
          onClick={() => navigate(`/reports/${result.patient_id}`, { state: { result, patient } })}
          className="btn-secondary"
        >
          <FileText className="w-4 h-4" />
          View Report
        </button>
        <button
          onClick={() => navigate(`/prediction/${patientId}`)}
          className="btn-primary"
        >
          <Brain className="w-4 h-4" />
          New Analysis
          <ChevronRight className="w-4 h-4" />
        </button>
      </div>
    </div>
  );
}
